{{- if .Values.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "k8s-aws-oidc-chart.fullname" . }}
  labels:
    {{- include "k8s-aws-oidc-chart.labels" . | nindent 4 }}
rules:
  - apiGroups:
      - ""
    resources:
      - secrets
    resourceNames:
      - {{ include "k8s-aws-oidc-chart.stateSecretName" . }}
    verbs:
      - get
      - update
      - patch
  - apiGroups:
      - ""
    resources:
      - events
    verbs:
      - get
      - create
      - patch
  {{- if .Values.leaderElection.enabled }}
  - apiGroups:
      - coordination.k8s.io
    resources:
      - leases
    resourceNames:
      - {{ include "k8s-aws-oidc-chart.leaseName" . }}
    verbs:
      - get
      - update
      - patch
  {{- end }}
{{- end }}
