{{- if .Values.tailscale.stateSecret.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "k8s-aws-oidc-chart.stateSecretName" . }}
  labels:
    {{- include "k8s-aws-oidc-chart.labels" . | nindent 4 }}
type: Opaque
data: {}
{{- end }}
