name: Release

on:
  push:
    tags:
      - "v*"

permissions: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

jobs:
  release:
    uses: ./.github/workflows/reusable-release.yml
    permissions:
      contents: write
      packages: write
      id-token: write
      attestations: write
      artifact-metadata: write
    secrets:
      release_token: ${{ secrets.GITHUB_TOKEN }}
